### ISSUE TITLE
Login via Github failed

### ISSUE THREAD

**Issue by seanlinsley** [BotBotMe/botbot-web#122]
![screen shot 2015-01-02 at 2 41 26 pm](https://cloud.githubusercontent.com/assets/688886/5599002/a418ae16-928d-11e4-8693-83f545267096.png)

This is what I get when attempting to log in via Github. Let me know if you need more details. Note that trying a second time results in the same error.

**Comment by yml** [comment]
Thanks, I am able to reproduce this error.

```
Error message
botbot.apps.accounts.models:MultipleObjectsReturned: get() returned more than one User -- it returned 10!

Stack trace
Traceback (most recent call last):
File "/srv/botbot/local/lib/python2.7/site-packages/newrelic-2.22.1.20/newrelic/hooks/framework_django.py", line 492, in wrapper return wrapped(*args, **kwargs)
File "/srv/botbot/local/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 53, in view return self.dispatch(request, *args, **kwargs)
File "/srv/botbot/local/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 112, in dispatch return complete_social_login(request, login)
File "/srv/botbot/local/lib/python2.7/site-packages/allauth/socialaccount/helpers.py", line 110, in complete_social_login get_adapter().pre_social_login(request, sociallogin)
File "/srv/botbot/src/botbot_me/botbot_me/apps/core/adapters.py", line 13, in pre_social_login user = User.objects.get(email=sociallogin.account.user.email)
File "/srv/botbot/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get return self.get_queryset().get(*args, **kwargs)
File "/srv/botbot/local/lib/python2.7/site-packages/django/db/models/query.py", line 313, in get (self.model._meta.object_name, num))
MultipleObjectsReturned: get() returned more than one User -- it returned 10!
```

**Comment by yml** [comment]
@seanlinsley the problem should be fixed, thank you for reporting it.

**Comment by seanlinsley** [comment]
Thanks!
